apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
spec: # spec do deployment
  replicas: 1

  selector: # selector utilizado para criar o service
    matchLabels:
      app: mysql-server
      tier: db

  template: # referente ao POD
    metadata:
      labels:
        app: mysql-server
        tier: db
    spec: # spec do POD
      containers:
      - name: mysql-server
        image: mysql:5.7
        args:
          - "--ignore-db-dir=lost+found"
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
        resources:
          requests:
            memory: "500Mi"
            cpu: "200m"
          limits:
            cpu: "250m"
            memory: "600Mi"
        ports:
        - containerPort: 3306
        volumeMounts: # monta o volume efetivamente
          - mountPath: /var/lib/mysql
            name: mysql-persistent-storage
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
              claimName: mysql-pv-claim